### ISSUE TITLE
file not found errro

### ISSUE THREAD

**Issue by rajatanand86** [XamHans/video-2-text#4]
Hi I am getting a file not found error. can you please help?

Traceback (most recent call last):
  File "C:\Users\DELL\Desktop\video2txt\video2txtenv\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\DELL\Desktop\video2txt\video-2-text\webserver\app.py", line 66, in <module>
    main()
  File "C:\Users\DELL\Desktop\video2txt\video-2-text\webserver\app.py", line 43, in main
    transcript = transcribeVideoOrchestrator(url, model)
  File "C:\Users\DELL\Desktop\video2txt\video-2-text\webserver\businessLogic.py", line 10, in transcribeVideoOrchestrator
    transcription = transcribe(video, model_name)
  File "C:\Users\DELL\Desktop\video2txt\video-2-text\webserver\businessLogic.py", line 20, in transcribe
    result = model.transcribe(video['path'], )
  File "C:\Users\DELL\Desktop\video2txt\video2txtenv\lib\site-packages\whisper\transcribe.py", line 121, in transcribe
    mel = log_mel_spectrogram(audio, padding=N_SAMPLES)
  File "C:\Users\DELL\Desktop\video2txt\video2txtenv\lib\site-packages\whisper\audio.py", line 143, in log_mel_spectrogram
    audio = load_audio(audio)
  File "C:\Users\DELL\Desktop\video2txt\video2txtenv\lib\site-packages\whisper\audio.py", line 60, in load_audio
    out = run(cmd, capture_output=True, check=True).stdout
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by rajatanand86** [comment]
got it. ffmpeg was not installed.
