### ISSUE TITLE
Can't download video with PyTube

### ISSUE THREAD

**Issue by phanxuanduc1996** [XamHans/video-2-text#5]
Hi @XamHans ,
I am trying your source code. I installed Python lib and ran the app. But when I tried to use the application, the source couldn't download the YouTube link and gave a Timeout error. I tried to fix it but was not successful. So, can you help me to fix it?
Thanks so much.

![image](https://github.com/XamHans/video-2-text/assets/14285912/1769a47a-bdd7-4716-9f92-381a99294171)

**Comment by tzhou8** [comment]
You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.71.11:8501

Attempt 1 failed: <urlopen error [Errno 60] Operation timed out>. Retrying...
Attempt 1 failed: <urlopen error [Errno 60] Operation timed out>. Retrying...
Attempt 2 failed: <urlopen error [Errno 60] Operation timed out>. Retrying...
Attempt 2 failed: <urlopen error [Errno 60] Operation timed out>. Retrying...
All 3 attempts failed.
2024-09-16 15:08:01.995 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/opt/anaconda3/envs/v2t/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/taozhou/Documents/GitHub/video-2-text/webserver/app.py", line 83, in <module>
    main()
  File "/Users/taozhou/Documents/GitHub/video-2-text/webserver/app.py", line 60, in main
    transcript = transcribeVideoOrchestrator(url, model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/taozhou/Documents/GitHub/video-2-text/webserver/businessLogic.py", line 12, in transcribeVideoOrchestrator
    video = downloadYoutubeVideo(youtube_url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/taozhou/Documents/GitHub/video-2-text/webserver/businessLogic.py", line 34, in downloadYoutubeVideo
    file_path = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download()
                ^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
                                                  ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>
All 3 attempts failed.
2024-09-16 15:08:05.609 Uncaught app exception
Traceback (most recent call last):
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/opt/anaconda3/envs/v2t/lib/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/socket.py", line 865, in create_connection
    raise exceptions[0]
  File "/opt/anaconda3/envs/v2t/lib/python3.12/socket.py", line 850, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 590, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/taozhou/Documents/GitHub/video-2-text/webserver/app.py", line 83, in <module>
    main()
  File "/Users/taozhou/Documents/GitHub/video-2-text/webserver/app.py", line 60, in main
    transcript = transcribeVideoOrchestrator(url, model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/taozhou/Documents/GitHub/video-2-text/webserver/businessLogic.py", line 12, in transcribeVideoOrchestrator
    video = downloadYoutubeVideo(youtube_url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/taozhou/Documents/GitHub/video-2-text/webserver/businessLogic.py", line 34, in downloadYoutubeVideo
    file_path = yt.streams.filter(progressive=True, file_extension='mp4').order_by('resolution').desc().first().download()
                ^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/__main__.py", line 295, in streams
    self.check_availability()
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/__main__.py", line 210, in check_availability
    status, messages = extract.playability_status(self.watch_html)
                                                  ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/__main__.py", line 102, in watch_html
    self._watch_html = request.get(url=self.watch_url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/request.py", line 53, in get
    response = _execute_request(url, headers=extra_headers, timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/site-packages/pytube/request.py", line 37, in _execute_request
    return urlopen(request, timeout=timeout)  # nosec
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/v2t/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>


Yes, I aslo encoutered the same issue.

**Comment by tzhou8** [comment]
mark
